import enum


class RunType(str, enum.Enum):
    ORIGINAL = "ORIGINAL"
    REPRODUCTION = "REPRODUCTION"
    INVESTIGATION = "INVESTIGATION"


class RunStatus(str, enum.Enum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ArtifactType(str, enum.Enum):
    MODEL = "MODEL"
    LOG = "LOG"
    METRIC_DUMP = "METRIC_DUMP"
    STDOUT = "STDOUT"
    STDERR = "STDERR"
    OTHER = "OTHER"


class DeterminismIntent(str, enum.Enum):
    REQUESTED = "REQUESTED"
    NOT_REQUESTED = "NOT_REQUESTED"


class DeterminismClassification(str, enum.Enum):
    DETERMINISTIC = "DETERMINISTIC"
    CONDITIONALLY_DETERMINISTIC = "CONDITIONALLY_DETERMINISTIC"
    NON_DETERMINISTIC = "NON_DETERMINISTIC"
    UNKNOWN = "UNKNOWN"


class ComparisonStatus(str, enum.Enum):
    SAME = "SAME"
    DIFFERENT = "DIFFERENT"
    UNKNOWN = "UNKNOWN"
    PARTIALLY_MATCHING = "PARTIALLY_MATCHING"
    NOT_COMPARABLE = "NOT_COMPARABLE"


class DifferenceCategory(str, enum.Enum):
    CODE = "CODE"
    DATASET = "DATASET"
    ENVIRONMENT = "ENVIRONMENT"
    CONFIGURATION = "CONFIGURATION"
    RANDOMNESS = "RANDOMNESS"
    METRICS = "METRICS"


class DifferenceType(str, enum.Enum):
    VALUE_CHANGED = "VALUE_CHANGED"
    MISSING_IN_BASE = "MISSING_IN_BASE"
    MISSING_IN_COMPARE = "MISSING_IN_COMPARE"
    TYPE_CHANGED = "TYPE_CHANGED"
    ADDED = "ADDED"
    REMOVED = "REMOVED"


class Severity(str, enum.Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class Confidence(str, enum.Enum):
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


class ReproducibilityClassification(str, enum.Enum):
    EXACTLY_REPRODUCIBLE = "EXACTLY_REPRODUCIBLE"
    REPRODUCIBLE_WITHIN_TOLERANCE = "REPRODUCIBLE_WITHIN_TOLERANCE"
    CONDITIONALLY_REPRODUCIBLE = "CONDITIONALLY_REPRODUCIBLE"
    PARTIALLY_REPRODUCIBLE = "PARTIALLY_REPRODUCIBLE"
    NOT_REPRODUCIBLE = "NOT_REPRODUCIBLE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    NOT_COMPARABLE = "NOT_COMPARABLE"


class JobType(str, enum.Enum):
    RUN_EXPERIMENT = "RUN_EXPERIMENT"
    COMPARE_RUNS = "COMPARE_RUNS"
    CAPTURE_PROVENANCE = "CAPTURE_PROVENANCE"


class JobStatus(str, enum.Enum):
    CREATED = "CREATED"
    QUEUED = "QUEUED"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
