"""initial schema

Revision ID: c6dd8a238406
Revises: 
Create Date: 2026-09-15 19:46:38.622354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c6dd8a238406'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_dataset_project_name')
    )
    op.create_table('experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workload_type', sa.String(length=50), nullable=False),
    sa.Column('entrypoint_script', sa.String(length=300), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_experiment_project_name')
    )
    op.create_table('dataset_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('schema_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('stats_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('duplicate_row_count', sa.Integer(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('source_uri', sa.String(length=1000), nullable=True),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'content_hash', name='uq_datasetversion_dataset_hash')
    )
    op.create_table('experiment_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('run_type', sa.Enum('ORIGINAL', 'REPRODUCTION', 'INVESTIGATION', name='runtype'), nullable=False),
    sa.Column('parent_run_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'QUEUED', 'EXECUTING', 'COMPLETED', 'FAILED', 'CANCELLED', name='runstatus'), nullable=False),
    sa.Column('triggered_by_user_id', sa.UUID(), nullable=True),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['experiment_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('artifact_type', sa.Enum('MODEL', 'LOG', 'METRIC_DUMP', 'STDOUT', 'STDERR', 'OTHER', name='artifacttype'), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('code_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('vcs_present', sa.Boolean(), nullable=False),
    sa.Column('git_commit_sha', sa.String(length=64), nullable=True),
    sa.Column('git_branch', sa.String(length=200), nullable=True),
    sa.Column('is_dirty', sa.Boolean(), nullable=False),
    sa.Column('is_detached_head', sa.Boolean(), nullable=False),
    sa.Column('is_shallow_clone', sa.Boolean(), nullable=False),
    sa.Column('tree_fingerprint_hash', sa.String(length=64), nullable=True),
    sa.Column('fingerprint_algorithm_version', sa.String(length=20), nullable=False),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('canonical_json', sa.Text(), nullable=False),
    sa.Column('configuration_fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('environments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('os_name', sa.String(length=100), nullable=True),
    sa.Column('os_version', sa.String(length=200), nullable=True),
    sa.Column('architecture', sa.String(length=50), nullable=True),
    sa.Column('python_version', sa.String(length=50), nullable=True),
    sa.Column('hostname', sa.String(length=200), nullable=True),
    sa.Column('cpu_model', sa.String(length=200), nullable=True),
    sa.Column('cpu_count', sa.Integer(), nullable=True),
    sa.Column('ram_total_mb', sa.Integer(), nullable=True),
    sa.Column('gpu_present', sa.Boolean(), nullable=False),
    sa.Column('gpu_model', sa.String(length=200), nullable=True),
    sa.Column('cuda_version', sa.String(length=50), nullable=True),
    sa.Column('environment_fingerprint_hash', sa.String(length=64), nullable=True),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('experiment_comparisons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('base_run_id', sa.UUID(), nullable=False),
    sa.Column('compare_run_id', sa.UUID(), nullable=False),
    sa.Column('code_status', sa.Enum('SAME', 'DIFFERENT', 'UNKNOWN', 'PARTIALLY_MATCHING', 'NOT_COMPARABLE', name='comparisonstatus'), nullable=False),
    sa.Column('dataset_status', sa.Enum('SAME', 'DIFFERENT', 'UNKNOWN', 'PARTIALLY_MATCHING', 'NOT_COMPARABLE', name='comparisonstatus'), nullable=False),
    sa.Column('environment_status', sa.Enum('SAME', 'DIFFERENT', 'UNKNOWN', 'PARTIALLY_MATCHING', 'NOT_COMPARABLE', name='comparisonstatus'), nullable=False),
    sa.Column('configuration_status', sa.Enum('SAME', 'DIFFERENT', 'UNKNOWN', 'PARTIALLY_MATCHING', 'NOT_COMPARABLE', name='comparisonstatus'), nullable=False),
    sa.Column('randomness_status', sa.Enum('SAME', 'DIFFERENT', 'UNKNOWN', 'PARTIALLY_MATCHING', 'NOT_COMPARABLE', name='comparisonstatus'), nullable=False),
    sa.Column('metrics_status', sa.Enum('SAME', 'DIFFERENT', 'UNKNOWN', 'PARTIALLY_MATCHING', 'NOT_COMPARABLE', name='comparisonstatus'), nullable=False),
    sa.Column('comparison_algorithm_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['base_run_id'], ['experiment_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['compare_run_id'], ['experiment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_run_id', 'compare_run_id', name='uq_comparison_base_compare')
    )
    op.create_table('fingerprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=True),
    sa.Column('dataset_hash', sa.String(length=64), nullable=True),
    sa.Column('environment_hash', sa.String(length=64), nullable=True),
    sa.Column('configuration_hash', sa.String(length=64), nullable=True),
    sa.Column('randomness_hash', sa.String(length=64), nullable=True),
    sa.Column('composite_hash', sa.String(length=64), nullable=False),
    sa.Column('fingerprint_version', sa.String(length=20), nullable=False),
    sa.Column('missing_components_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Numeric(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'name', name='uq_metric_run_name')
    )
    op.create_table('provenance_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('ref_table', sa.String(length=100), nullable=False),
    sa.Column('ref_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('randomness_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('python_seed', sa.Integer(), nullable=True),
    sa.Column('numpy_seed', sa.Integer(), nullable=True),
    sa.Column('other_seeds_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('determinism_intent', sa.Enum('REQUESTED', 'NOT_REQUESTED', name='determinismintent'), nullable=False),
    sa.Column('determinism_classification', sa.Enum('DETERMINISTIC', 'CONDITIONALLY_DETERMINISTIC', 'NON_DETERMINISTIC', 'UNKNOWN', name='determinismclassification'), nullable=False),
    sa.Column('randomness_fingerprint_hash', sa.String(length=64), nullable=False),
    sa.Column('captured_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id')
    )
    op.create_table('run_dataset_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('dataset_version_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['run_id'], ['experiment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_id', 'dataset_version_id', 'role', name='uq_rundatasetlink_run_version_role')
    )
    op.create_table('code_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code_snapshot_id', sa.UUID(), nullable=False),
    sa.Column('relative_path', sa.String(length=1000), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['code_snapshot_id'], ['code_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_snapshot_id', 'relative_path', name='uq_codefile_snapshot_path')
    )
    op.create_table('dependencies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('environment_id', sa.UUID(), nullable=False),
    sa.Column('package_name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('environment_id', 'package_name', name='uq_dependency_env_package')
    )
    op.create_table('differences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comparison_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('CODE', 'DATASET', 'ENVIRONMENT', 'CONFIGURATION', 'RANDOMNESS', 'METRICS', name='differencecategory'), nullable=False),
    sa.Column('field', sa.String(length=300), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('difference_type', sa.Enum('VALUE_CHANGED', 'MISSING_IN_BASE', 'MISSING_IN_COMPARE', 'TYPE_CHANGED', 'ADDED', 'REMOVED', name='differencetype'), nullable=False),
    sa.Column('evidence_source', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('confidence', sa.Enum('HIGH', 'MEDIUM', 'LOW', name='confidence'), nullable=False),
    sa.Column('is_potential_contributor', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['experiment_comparisons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_type', sa.Enum('RUN_EXPERIMENT', 'COMPARE_RUNS', 'CAPTURE_PROVENANCE', name='jobtype'), nullable=False),
    sa.Column('related_run_id', sa.UUID(), nullable=True),
    sa.Column('related_comparison_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('CREATED', 'QUEUED', 'EXECUTING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_comparison_id'], ['experiment_comparisons.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_run_id'], ['experiment_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('provenance_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_node_id', sa.UUID(), nullable=False),
    sa.Column('to_node_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_node_id'], ['provenance_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_node_id'], ['provenance_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reproducibility_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comparison_id', sa.UUID(), nullable=False),
    sa.Column('classification', sa.Enum('EXACTLY_REPRODUCIBLE', 'REPRODUCIBLE_WITHIN_TOLERANCE', 'CONDITIONALLY_REPRODUCIBLE', 'PARTIALLY_REPRODUCIBLE', 'NOT_REPRODUCIBLE', 'INSUFFICIENT_EVIDENCE', 'NOT_COMPARABLE', name='reproducibilityclassification'), nullable=False),
    sa.Column('rationale_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('algorithm_version', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comparison_id'], ['experiment_comparisons.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comparison_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reproducibility_assessments')
    op.drop_table('provenance_edges')
    op.drop_table('jobs')
    op.drop_table('differences')
    op.drop_table('dependencies')
    op.drop_table('code_files')
    op.drop_table('run_dataset_links')
    op.drop_table('randomness_profiles')
    op.drop_table('provenance_nodes')
    op.drop_table('metrics')
    op.drop_table('fingerprints')
    op.drop_table('experiment_comparisons')
    op.drop_table('environments')
    op.drop_table('configurations')
    op.drop_table('code_snapshots')
    op.drop_table('artifacts')
    op.drop_table('experiment_runs')
    op.drop_table('dataset_versions')
    op.drop_table('experiments')
    op.drop_table('datasets')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('users')
    # ### end Alembic commands ###
